rta:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: KafkaEngine
      host: localhost
      port: 8123
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: False